### ISSUE TITLE
Unable to Scroll Code Blocks Horizontally

### ISSUE THREAD

**Issue by dozn** [odin-lang/odin-lang.org#138]
I can't scroll horizontally on [almost every code block](https://pkg.odin-lang.org/core/encoding/json/#parse_string).

[The specification block](https://pkg.odin-lang.org/core/encoding/json/#Specification) as well as [unquote_string](https://pkg.odin-lang.org/core/encoding/json/#unquote_string) however, _do_ work.

Tested on both Chromium and Firefox on Linux, as well as Firefox on a separate Windows machine.

**Comment by hasanyasin** [comment]
This was caused by headings overlapping the preceding content. Why it works for `unquote_string` is thanks to the paragraph below the code block which pushes down the following heading, eliminating the overlap.

It is now fixed and should be deployed tomorrow as the doc site is rebuilt at midnight.

@dozn, please check again tomorrow and confirm if solved so the issue can be closed.

**Comment by dozn** [comment]
Confirmed fixed—thanks!
