### ISSUE TITLE
Incorrect information about accessing invalid memory through dereferencing

### ISSUE THREAD

**Issue by akbulutdora** [odin-lang/odin-lang.org#188]
The [documentation](https://odin-lang.org/docs/overview/#address-operator) states that dereferencing an uninitialized pointer will cause a `panic`. However it causes a segfault.

**Comment by gingerBill** [comment]
Technically both are wrong.

On all the platforms except WASM, dereferencing the `nil` pointer will cause a segmentation fault. On WASM, this is currently perfectly valid to do (because WASM's memory model is pretty bad).

To be more correct, it might better to phrase it as something like the following:

> platform specific behaviour, usually a segmentation fault on most platforms
